### ISSUE TITLE
Deployment of ACR Agent Pools should be configurable since it is in preview 

### ISSUE THREAD

**Issue by mattcowen** [Azure/Aks-Construction#135]
**Is your feature request related to a problem? Please describe.**
Deploying to Ent Scale context where landing zone subs are restricted to UK South/West causes an error since ACR agent pools are not in UK yet while the feature is in preview.

**Describe the solution you'd like**
A parameter to disable ACR agent pool deployment

**Describe alternatives you've considered**
Deploying to sandbox mgmt group however they want to deploy for prod use.

**Comment by khowling** [comment]
Thanks @mattcowen !  The switch for the ACR Private Pool is in the addons tab, so you should be able to disable ok.  But It was not made clear that the feature is in preview.  So updated the option label in the addons tab to clarify & ensure its behind the 'preview' switch on the main deployment tab

**Comment by khowling** [comment]
@Gordonby linked PR awaiting approval
