### ISSUE TITLE
Custom Networking does not reflect changes

### ISSUE THREAD

**Issue by sbugalski** [Azure/Aks-Construction#14]
Setting up custom Networking does not reflect changes for generated CLI commands.

![image](https://user-images.githubusercontent.com/45152735/124613261-5561a500-de73-11eb-9fd8-c93c6e8dbfbb.png)
![image](https://user-images.githubusercontent.com/45152735/124613311-614d6700-de73-11eb-8c4e-7cdc944dbb77.png)

**Comment by khowling** [comment]
@sbugalski thank you very much for logging the issue, this was an oversight, PR submitted

**Comment by khowling** [comment]
Fixed
