### ISSUE TITLE
No autoupgrade preview feature info

### ISSUE THREAD

**Issue by sbugalski** [Azure/Aks-Construction#15]
Hello,

When tried to create cluster with auto-upgrade feature it didn't work resulting in:
`{"error":{"code":"InvalidTemplateDeployment","message":"The template deployment 'main' is not valid according to the validation procedure. The tracking id is '704c144a-8d29-4a66-9cea-f58a8df88f96'. See inner errors for details.","details":[{"code":"BadRequest","message":"Provisioning of resource(s) for container service aks-az-k8s-7qkc in resource group az-k8s-7qkc-rg failed. Message: {\n  \"code\": \"BadRequest\",\n  \"message\": \"Feature Microsoft.ContainerService/AutoUpgradePreview is not enabled. Please see https://aka.ms/aks/previews for how to enable features.\"\n }. Details: "}]}}
`

It's worth to add note "Ensure you register for this preview feature [here](https://docs.microsoft.com/en-us/azure/aks/upgrade-cluster)"

**Comment by khowling** [comment]
Changed! thank you for reporting.
