### ISSUE TITLE
Lingering ACR Private pool compute prevents vnet and Resource Group from being deleted

### ISSUE THREAD

**Issue by RTmtfiallos** [Azure/Aks-Construction#178]
**Describe the bug**
Cannot delete resource group created by AKS-Construction.
When deleting the resource group all resources were deleted except the vnet that was generated.
Unable to delete the following resource type: **Scale set instance**
When clicking the Scale set instance I get a 'No Access' error.
Unable to delete this resource, thus not the resource group.

When trying to redeploy AKS to this resource group I receive the following error:
{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"DeploymentFailed\",\r\n        \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.\",\r\n        \"details\": [\r\n          {\r\n            \"code\": \"BadRequest\",\r\n        \"message\": \"{\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"RoleAssignmentUpdateNotPermitted\\\",\\r\\n    \\\"message\\\": \\\"Tenant ID, application ID, principal ID, and scope are not allowed to be updated.\\\\\r\\n  }\\r\\n}\\r\n          }\r\n        ]\r\n      }\r\n    ]\r\n  }\r\n}"}]}}

Session ID
d610bcdf58b647eab80777fa28968d3c
Resource ID
/subscriptions/ omitted /resourceGroups/ap-crabcdsaksdevtptmkhi5k7v5m-private-pool-81e/providers/Microsoft.Compute/virtualMachineScaleSets/crabcdsaksdevtptmkhi5k7v5m-private-pool-81e-0
Extension
HubsExtension
Content
ResourceMenuBlade
Error code
401
Details
You do not have authorization to access this resource.

Resource ID: /subscriptions/ omitted /resourceGroups/ap-crabcdsaksdevtptmkhi5k7v5m-private-pool-81e/providers/Microsoft.Compute/virtualMachineScaleSets/crabcdsaksdevtptmkhi5k7v5m-private-pool-81e-0

Status Code: 401

Status Message: The access token is from the wrong issuer 'https://sts.windows.net/ omitted /'. It must match the tenant 'https://sts.windows.net/33e01921-4d64-4f8c-a055-5bdaffd5e33d/' associated with this subscription. Please use the authority (URL) 'https://login.windows.net/33e01921-4d64-4f8c-a055-5bdaffd5e33d' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later.

**To Reproduce**
1. Deployed in different tenant and subscription
2. Tried to delete resource group
3. same resource unable to delete

**Expected behavior**
Able to delete resource group created by AKS-Construction

**Screenshots**
![error1](https://user-images.githubusercontent.com/55808899/149009071-eb84cca1-e876-4de0-a8c7-ba3434a508d2.jpg)
![error2](https://user-images.githubusercontent.com/55808899/149009475-946770b3-f629-474b-b8d0-bd984d00677a.jpg)

![error3](https://user-images.githubusercontent.com/55808899/149010319-450b9204-7ea0-47be-b4d0-e7eee4225377.jpg)

**Additional context**
![error1](https://user-images.githubusercontent.com/55808899/149008966-98ff32a5-70c2-4112-a2c2-d5d30f19b206.jpg)

**Comment by Gordonby** [comment]
Thank you for raising this @RTmtfiallos , I also have the same issue occur in my subscription.

Raised internally, initial inspection is that this is a issue related to the ACR Private Agent Pools feature which is currently in preview.

**Comment by RTmtfiallos** [comment]
So what is the recourse or resolution to remove this resource?
Thank you

**Comment by Gordonby** [comment]
I've been in contact with the engineering team, and they've fixed the issue in my subscription. Can you email me your subscription id?  I'll forward to the team for the same action. gordon.byers@microsoft.com

Sorry about this. The team is separately investigating the root cause.

**Comment by RTmtfiallos** [comment]
Will do and Thank you!

We will proceed without acrPrivatePool for now.

**Comment by Gordonby** [comment]
Been advised that affected subscriptions have been fixed.... So I don't need the subscriptionId.

You can use ACR pool, but please delete the pool before deleting the ACR until the issue has been fixed.

**Comment by Gordonby** [comment]
> Thank you!
> 
> I'll ask the client how they want to proceed.
> 
> As for the design, will proceed without acrPrivatePool for now. Super happy that it was only affecting the acr and nothing else substantial to the overall private design.

Indeed.  The issue seems related to cleanup sequencing.

**Comment by Gordonby** [comment]
Need to test to see if this is fixed 😶

**Comment by Gordonby** [comment]
## Tested

1. Deployed Private Pool
2. Confirmed compute is in subnet
![image](https://user-images.githubusercontent.com/17914476/152997457-28118cca-3931-4450-aa43-1632ed685710.png)
3. Delete ACR resource first
![image](https://user-images.githubusercontent.com/17914476/152997553-626fe3e3-d639-4e99-abf9-ea176c297434.png)
4. Check subnet for residual ACR compute
(it's gone! 😮 🏅   🚀 )
5. Delete the rest of the resources.
(No problemos)
