### ISSUE TITLE
openjdk fails during upgrade

### ISSUE THREAD

**Issue by RTmtfiallos** [Azure/Aks-Construction#181]
**Describe the bug**
One of the post-deployment tasks is to export and upgrade the openjdk-demo.
The upgrade fails.  It may be related to the regex and when defining the dynamic value, i.e. azure-openjdk-demo-kv-ABCDSev.
The value comes back as invalid metatdata.
This results in the pod not coming up and openjdk functionality lost.

**To Reproduce**
1. use ABCDSev as the cluster name

**Screenshots**

![error34](https://user-images.githubusercontent.com/55808899/149313906-a3013e2a-382b-430a-9b01-f81fa2b71d11.jpg)

**Additional context**
Any thoughts on how to proceed and recover?

**Comment by Gordonby** [comment]
You're going to need to downcase the name.
The error message specifies that the secrets metadata.name must be lower case.

@khowling - any additional thoughts?

**Comment by RTmtfiallos** [comment]
I went ahead and tried this before I saw your suggestion, so I'm glad we're in sync.

I now have it where both the post deployment scripts run successfully, without any errors.

I modified them to run without invoking kubectl since I'm running from a jump box.

Now the externaldns pod is in a crash loop and the other one fails to start because it has a connection refused from the CSI driver.  This is for the storage so that makes sense why I won't start the pot up and I think it's a completely separate issue than the external DNS.

I now see every time I ran the second script it generated more secrets.

I'm standing up another cluster on the side but I want to try to work through this.

I've modified the shell scripts so they can run remotely with the invoke commands or without it on a local jump box.

There was an issue with some of the arguments and I had to clean a few up to get it to actually run clean, and a relatively confident that it's working because I got issued a cert.  The arguments were the -file and the --file back to back.

Any thoughts on how to recover at a high level?

I'll attach screenshots and logs here in a little bit.

Clever scripting there dude on the waiting for the self signed cert to come back via the temporary azure storage. I increased the sleep time to 2 minutes because it didn't come back in time on a few of them. 
Slick.  😉

**Comment by RTmtfiallos** [comment]
Finally got it figured out and everything appears up and running.

Thanks again for the help.
Let me know if you want me to pull that bit and write a quick start guide and overview of the moving pieces.

**Comment by Gordonby** [comment]
Glad you got it sorted. 😀

A quickstart doc sounds cool, it's always good to get other perspectives on the approach. If you had your own blog we could link out to it from this repo, or if you wanted it in this repo we'd need to figure the best place for it to slot into.
