### ISSUE TITLE
List of deployable locations in the helper wizard should be auto-populated

### ISSUE THREAD

**Issue by PaulMaddox** [Azure/AKS-Construction#243]
**Is your feature request related to a problem? Please describe.**
Currently the list of locations that can be deployed to via the helper wizard is hardcoded. E.g.

https://github.com/Azure/AKS-Construction/blob/88be947c9ada7c92805b3251a931e2c7aee634e3/helper/src/components/deployTab.js#L307-L328

**Describe the solution you'd like**
This list should be auto-populated based on the available locations that support AKS.

**Describe alternatives you've considered**
n/a

**Additional context**
If someone can point me in the direction of a published JSON file/API that includes the locations and their service availability matrix, I can put a PR together.

**Comment by Gordonby** [comment]
@khowling - perhaps we can generate the json during the release workflow. Alternatively we can just maintain the json in the repo, but i think creating it on demand in the release might be cool.

**Comment by Gordonby** [comment]
@fireblade95402 - This one up your street?

**Comment by fireblade95402** [comment]
Just noticed this one now. As we have a huge number of locations. I have previously created a file that populates the locations. As this file is also used to generate the VM SKU list. 

I suggest we keep the current logic and update the [location](https://github.com/Azure/AKS-Construction/blob/main/helper/src/locations.json)  files with any new required locations for the helper. 
 Current list is:
 
 [
    { "key": "europe", "text": "Europe", "itemType": 2},
    { "key": "WestEurope", "text": "West Europe"},
    { "key": "NorthEurope", "text": "North Europe"},
    { "key": "UKSouth", "text": "UK South"},
    { "key": "UKWest", "text": "UK West" },
    { "key": "middleeast", "text": "Middle East", "itemType": 2 },
    { "key": "UAENorth", "text": "UAE North" },
    { "key": "america", "text": "North America", "itemType": 2 },
    { "key": "CentralUS", "text": "Central US" },
    { "key": "EastUS", "text": "East US" },
    { "key": "EastUS2", "text": "East US2" },
    { "key": "WestUS", "text": "West US" },
    { "key": "WestUS2", "text": "West US2" },
    { "key": "WestCentralUS", "text": "West Central US" },
    { "key": "canada", "text": "Canada", "itemType": 2 },
    { "key": "CanadaCentral", "text": "Canada Central" },
    { "key": "CanadaEast", "text": "Canada East" }
    ]
