### ISSUE TITLE
Support CSI feature - Secret Rotation

### ISSUE THREAD

**Issue by Gordonby** [Azure/AKS-Construction#247]
Add support for auto rotation of secret objects
- [x] Add 2 new parameters to the bicep
- [x] Add new capability to the bicep
- [x] Add new UI components for boolean and integer parameters

## Context

As per these [docs](https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver#enable-and-disable-autorotation).
Secret rotation can be enabled on the CSI driver.

> When the Azure Key Vault Provider for Secrets Store CSI Driver is enabled, it updates the pod mount and the Kubernetes secret that's defined in the secretObjects field of SecretProviderClass. It does so by polling for changes periodically, based on the rotation poll interval you've defined. The default rotation poll interval is 2 minutes.

## Arm / Bicep - default 2m rotation

```json
"addonProfiles": {
    "azureKeyvaultSecretsProvider": {
      "config": {
        "enableSecretRotation": "true"
      },
      "enabled": true,
      "identity": {
        "clientId": "redacted",
        "objectId": "redacted",
        "resourceId": "redacted"
      }
    }
}
```

## Arm / Bicep - custom 5m rotation

```json
"addonProfiles": {
    "azureKeyvaultSecretsProvider": {
      "config": {
        "enableSecretRotation": "true",
        "rotationPollInterval": "5m"
      },
      "enabled": true,
      "identity": {
        "clientId": "redacted",
        "objectId": "redacted",
        "resourceId": "redacted"
      }
    }
}
```

**Comment by liammoat** [comment]
@Gordonby I'd be happy to pick this up
