### ISSUE TITLE
KMS etcd encryption

### ISSUE THREAD

**Issue by Gordonby** [Azure/AKS-Construction#303]
Leverage Key Management Service (KMS) plugin with  Azure Key Vault to encrypt etcd data.

https://docs.microsoft.com/en-us/azure/aks/use-kms-etcd-encryption

## Design notes

KMS etcd encryption doesn't work with System-Assigned Managed Identity

## Design decisions

Do we want a new, separate key vault for KMS etcd data?
Do we want to easily facilitate BYOK for KV?

**Comment by Gordonby** [comment]
This is a super valuable feature @Azure/bicep-maintainers 
There's integration in many areas. Someone want to pick up?

**Comment by Gordonby** [comment]
bicep schema

```bicep
      azureKeyVaultKms: {
        enabled: bool
        keyId: 'string'
        keyVaultNetworkAccess: 'string'
        keyVaultResourceId: 'string'
      }
```

**Comment by Gordonby** [comment]
AzureKeyVaultKms feature does not support cluster identity type SystemAssigned, supported value is 'UserAssigned'

**Comment by Gordonby** [comment]
It's not stale...  its wip 😅

**Comment by aknimbal** [comment]
Lol. Sorry, I know. I will change that

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
