### ISSUE TITLE
Web Application Routing (preview)

### ISSUE THREAD

**Issue by Gordonby** [Azure/AKS-Construction#306]
Implement support for https://docs.microsoft.com/en-us/azure/aks/web-app-routing

> When the solution's enabled, it configures an Ingress controller, SSL termination, Open Service Mesh (OSM) for E2E encryption of inter cluster communication. As applications are deployed, the solution also creates publicly accessible DNS names for application endpoints.

[Microsoft.ContainerService/managedClusters@2022-03-02-preview](https://docs.microsoft.com/en-us/azure/templates/microsoft.containerservice/managedclusters?tabs=bicep#managedclusteringressprofilewebapprouting)

### Bicep Schema

```bicep
    ingressProfile: {
      webAppRouting: {
        dnsZoneResourceId: 'string'
        enabled: bool
      }
    }
```

### Arm Sample Values

```json
"ingressProfile": {
    "webAppRouting": {
        "enabled": true
    }
}
```

### Sample Portal Config

![image](https://user-images.githubusercontent.com/17914476/173045478-2d48f0e8-9a54-4dfe-8218-ff069ee894b3.png)

**Comment by Gordonby** [comment]
This work is in https://github.com/Azure/AKS-Construction/tree/gb-clusterexten
However the end to end workflow of Web App Routing seems to be problematic at the moment. Pausing this work until it has been iterated on.

**Comment by Gordonby** [comment]
Part of the work for this was done in https://github.com/Azure/AKS-Construction/pull/380

**Comment by fgarciacode** [comment]
Hi I'm trying to enable this feature using the following bicep:
```bicep
resource k8s 'Microsoft.ContainerService/managedClusters@2023-11-01' = {
  name: name
  location: location
  identity: {
    type: 'SystemAssigned'
  }
  sku: {
    name: 'Base'
    tier: 'Free'
  }
  properties: {
    kubernetesVersion: '1.27.9'
    dnsPrefix: name
    agentPoolProfiles: [
      {
        mode: 'System'
        name: 'controlplane'
        vmSize: 'Standard_DS2_v2'
        osType: 'Linux'
        enableAutoScaling: true
        count: 3
        minCount: 1
        maxCount: 3
        vnetSubnetID: containerSubnetID
      }
    ]
    networkProfile: {
      networkPlugin: 'azure'
      serviceCidr: serviceAddressSpace
      dnsServiceIP: dnsServiceIP
    }
    addonProfiles: {
      webAppRouting: {
        enabled: true
      }
    }
  }
}
```

Is it available? or Is a way I can enable it using IaC?
