### ISSUE TITLE
Cannot Scale cluster provisioned with omsagent=false

### ISSUE THREAD

**Issue by khowling** [Azure/AKS-Construction#314]
Provisioned a cluster without omsagent, it provisioned successfully, but when trying to manually scale, get error:
```
(LinkedInvalidPropertyId) Property id '' at path 'properties.addonProfiles.omsagent.config.logAnalyticsWorkspaceResourceID' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'.
Code: LinkedInvalidPropertyId
```

scale command:
```
az aks scale --resource-group xx --name xx --nodepool-name npsystem --node-count 4
```
provision parameters include:
```
agentCount=2 \
upgradeChannel=stable \
JustUseSystemPool=true \
```

az aks show, shows
![image](https://user-images.githubusercontent.com/1034202/176656144-b1385722-a93d-49c8-84aa-9775fb75719c.png)

```

**Comment by Gordonby** [comment]
Love it when the RP works like this. 😁🤣🤣
Perhaps worth logging an issue on AKS that the enabled property is not being leveraged as part of the scale command.
