### ISSUE TITLE
Cannot deploy cluster if selecting Open Source & Private Cluster

### ISSUE THREAD

**Issue by khowling** [Azure/AKS-Construction#315]
Landing on the helper, selecting Open Source and Private should result in a deployable configuration, currently, it doesnt

![image](https://user-images.githubusercontent.com/1034202/176884922-172f5c5d-afd3-46c4-a1c9-6065b63dc0eb.png)

**Comment by Gordonby** [comment]
Is this still a problem @khowling ?

**Comment by Gordonby** [comment]
As per convo with Keith... We just need to downgrade a Validation Error message to a Warning.
