### ISSUE TITLE
By enabling the option "Configure NSG Flow logs" the deployment fails

### ISSUE THREAD

**Issue by amantaras** [Azure/AKS-Construction#352]
By enabling the option "Configure NSG Flow logs" the deployment fails

I think it is because the storage account to store the logs has an invalid name ("including dashes -" maybe??)

**Error**
{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"DeploymentFailed\",\r\n        \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.\",\r\n        \"details\": [\r\n          {\r\n            \"code\": \"BadRequest\",\r\n            \"message\": \"{\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"AccountNameInvalid\\\",\\r\\n    \\\"message\\\": \\\"stflowaz-6jion6efxdf5ml4 is not a valid storage account name. Storage account name must be between 3 and 24 characters in length and use numbers and lower-case letters only.\\\"\\r\\n  }\\r\\n}\"\r\n          }\r\n        ]\r\n      }\r\n    ]\r\n  }\r\n}"}]}}

**Comment by Gordonby** [comment]
yep, looks like our default resource name doesn't work.

need some cleansing logic put into the storage account name. var

**Comment by amantaras** [comment]
Thanks a lot for getting back!  :thumbsup:  
this is really good stuff!  🎆

**Comment by Gordonby** [comment]
Repro'd with

```bash
az deployment group create -g innerloop  -f bicep/main.bicep --parameters resourceName=az-k8s-bea2 JustUseSystemPool=true custom_vnet=true CreateNetworkSecurityGroups=true CreateNetworkSecurityGroupFlowLogs=true
```

Fixed in linked PR
