### ISSUE TITLE
Invalid Template Deployment when activating Defender for Containers in main.bicep

### ISSUE THREAD

**Issue by jmservera** [Azure/AKS-Construction#353]
**Describe the bug**

When setting the defenderForContainers param to true, the template validation fails with this error:

> InvalidTemplateDeployment - The template deployment 'main' is not valid according to the validation procedure. The tracking id is '5906c022-66da-42e2-8d32-a254e38e8ccc'. See inner errors for details.
GetLogAnalyticsWorkspaceError - Provisioning of resource(s) for container service aks-jmaks in resource group jmaksdemone failed. Message: Category: ClientError; Code: GetLogAnalyticsWorkspaceError; SubCode: ; Message: Unable to get log analytics workspace info. Resource ID: /subscriptions/b83ae1c9-4dcb-4d45-8b76-a813d212f36c/resourceGroups/jmaksdemone/providers/Microsoft.OperationalInsights/workspaces/log-jmaks. Details: Category: ClientError; Code: Unspecified; SubCode: ResourceNotFound; Message: ; InnerMessage: ; Dependency: Microsoft.OperationalInsights/workspaces; OrginalError: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.OperationalInsights/workspaces/log-jmaks' under resource group 'jmaksdemone' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"; AKSTeam: RP, Retriable: false. For more details about how to create and use log analytics workspace,  please refer to: https://aka.ms/new-log-analytics; InnerMessage: ; Dependency: ; OrginalError: %!s(<nil>); AKSTeam: . Details:

**To Reproduce**
Steps to reproduce the behavior: it is enough to run this simple command to use the template with only two params.

```bash
az deployment group create -g [your-rg] --template-file .\main.bicep --param defenderForContainers=true --param resourceName=[your-resource-name] --what-if  
```

**Expected behavior**

It should not fail.

**Additional context**

I tried to reproduce it myself in a simpler bicep file and it looks like it is not related to this template nor to bicep, but to how the validation seeks for an existing analytics workspace instead of waiting it to be created but reporting it here just in case.

**Comment by jmservera** [comment]
Building the bicep into a json template and deploying it from the Azure Portal raises the same error, it looks like it is some server validation code issue.

**Workaround**

Use incremental deployment to deploy everything and then run it again activating defender. This way it doesn't complain because the second time the workspace is already created.

**Comment by Gordonby** [comment]
Defender for containers activation is a little week in the RP.

I think this is because Azure Policy will most commonly be used to enabled it.

It's for this reason that we haven't lit the defender parameter up in the Deployment Helper UI... However it is in the bicep.
