### ISSUE TITLE
Powershell script in Deployment Helper

### ISSUE THREAD

**Issue by Gordonby** [Azure/AKS-Construction#359]
The Deployment Helper web app currently provides the AZ CLI commands to be run in a bash script.

It would be nice if we could add a toggle option for powershell users.

eg.

Bash;
```bash
az deployment group create -g innerloop  --template-uri https://github.com/Azure/AKS-Construction/releases/download/0.8.8/main.json --parameters \
	resourceName=az-k8s-fat1 \
        authorizedIPRanges="[\"1.2.3.4/32\"]"
```

Pwsh;
```powershell
az deployment group create -g innerloop  --template-uri https://github.com/Azure/AKS-Construction/releases/download/0.8.8/main.json --parameters `
   resourceName=az-k8s-fat1 `
   authorizedIPRanges="['1.2.3.4/32']"
```

**Comment by Gordonby** [comment]
Oooohh... Azure PowerShell, now there's a thought.  I was just thinking of calling az cli from Pwsh.

Sure, i think this becomes a good option for those PoSh people 😉

**Comment by fireblade95402** [comment]
I've got a draft created, but wondering if there's real benefit to maintain it. As there's an element of duplication between Bash and PowerShell. I've created a feature branch (mwg-powershell-helper) Be good to get views before I look to create a PR.

**Comment by fireblade95402** [comment]
That postdeploy.sh script will be the challenge. To move this one forward we'd need to rewrite it to run in PowerShell. I'll start to think about a solution here. Not too sure yet what the options are.

**Comment by Jaykul** [comment]
Speaking as a PowerShell MVP, I want to see this in PowerShell with the Az modules, but you've got four or five hundred lines of bash in postdeploy/scripts!  Assuming you're not going to ditch bash and tell everyone to install pwsh -- I don't think you _want_ anyone to put effort into porting that to PowerShell -- you'll just end up with two copies of the same functionality that you have to maintain...

**Comment by Gordonby** [comment]
It might be best to put this one on nice for the moment.

**Comment by fireblade95402** [comment]
I did start rewriting the bash script in PowerShell and got it to 90% ready, but again created tech. debt with the need to maintain 2 versions of the post deployment script

**Comment by fireblade95402** [comment]
I've started on the PowerShell script again to complete the last bits and pieces. Did loose a weeks work by forgetting to push a change :( My bad!
