### ISSUE TITLE
Azure KeyvaultSecretsProviderAddonFeatureFlagNotEnabled

### ISSUE THREAD

**Issue by larrywa** [Azure/Aks-Construction#36]
I have the latest version of the az preview installed in my command window. When I try to deploy a cluster using this tool, here is the full error:

{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations forusage details.","details":[{"code":"BadRequest","message":"{\r\n  \"code\": \"AzureKeyvaultSecretsProviderAddonFeatureFlagNotEnabled\",\r\n  \"message\": \"AzureKeyvaultSecretsProvider addon is not allowed since feature 'Microsoft.ContainerService/AKS-AzureKeyVaultSecretsProvider' is not enabled. Please see https://aka.ms/aks/previews for how to enable features.\"\r\n}"}]}}

My key vault provider is enabled in my subscription. Is there anything else I need to enable?

Larry

**Comment by Gordonby** [comment]
You'll need to register for the preview feature as described here : https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver#register-the-aks-azurekeyvaultsecretsprovider-preview-feature

![image](https://user-images.githubusercontent.com/17914476/133477805-9fe19f2f-78db-4a94-b54c-c787c88d878a.png)
