### ISSUE TITLE
AGIC not being enabled when using BYO networking

### ISSUE THREAD

**Issue by khowling** [Azure/AKS-Construction#373]
Reported by Partner: AGIC not being enabled when using BYO networking

**Comment by khowling** [comment]
need to repro

**Comment by khowling** [comment]
This is the logic can prevents the AGIC addon if BYO https://github.com/Azure/AKS-Construction/blob/main/bicep/main.bicep#L624

DEPLOY_APPGW_ADDON This is a circuit breaker to NOT deploy the appgw addon for BYO subnet, due to the error: IngressApplicationGateway addon cannot find Application Gateway.  Need to remove & retest to see if the new versions of AGIC has resololved this!

**Comment by Gordonby** [comment]
> This is the logic can prevents the AGIC addon if BYO https://github.com/Azure/AKS-Construction/blob/main/bicep/main.bicep#L624
> 
> DEPLOY_APPGW_ADDON This is a circuit breaker to NOT deploy the appgw addon for BYO subnet, due to the error: IngressApplicationGateway addon cannot find Application Gateway. Need to remove & retest to see if the new versions of AGIC has resololved this!

agreed, lets try to repro

**Comment by khowling** [comment]
testing 

### create byo network
```
az group create -n aksc-network
az group deployment create -g aksc-network -f ./samples/networkforbyo.bicep -p resourceName=aksc
-network
```

## deploy template

```
# Create Resource Group
az group create -l WestEurope -n az-k8s-71nm-rg

# Deploy template with in-line parameters
az deployment group create -g az-k8s-71nm-rg  --template-uri https://github.com/Azure/AKS-Construction/releases/download/0.8.9/main.json --parameters \
	resourceName=az-k8s-71nm \
	upgradeChannel=stable \
	agentCountMax=20 \
	byoAKSSubnetId=/subscriptions/xx/resourceGroups/aksc-network/providers/Microsoft.Network/virtualNetworks/vnet-aksc-network/subnets/aks-sn \
	byoAGWSubnetId=/subscriptions/xx/resourceGroups/aksc-network/providers/Microsoft.Network/virtualNetworks/vnet-aksc-network/subnets/appgw-sn \
	enable_aad=true \
	AksDisableLocalAccounts=true \
	enableAzureRBAC=true \
	adminPrincipalId=$(az ad signed-in-user show --query id --out tsv) \
	registries_sku=Premium \
	acrPushRolePrincipalId=$(az ad signed-in-user show --query id --out tsv) \
	omsagent=true \
	retentionInDays=30 \
	networkPolicy=azure \
	azurepolicy=audit \
	authorizedIPRanges="[\"xx\"]" \
	ingressApplicationGateway=true \
	appGWcount=0 \
	appGWsku=WAF_v2 \
	appGWmaxCount=10 \
	appgwKVIntegration=true \
	keyVaultAksCSI=true \
	keyVaultCreate=true \
	keyVaultOfficerRolePrincipalId=$(az ad signed-in-user show --query id --out tsv)

```
