### ISSUE TITLE
Pre-validation steps prior to deployment create

### ISSUE THREAD

**Issue by jvargh** [Azure/AKS-Construction#386]
`Feedback from Cloud Native Hack Hours`

**Is your feature request related to a problem? Please describe.**
Since addons fail takes ~10m to find out when the deployment create cmd is run, perhaps a validation step prior to check if all the pre-req's are in place 

**Describe the solution you'd like**
validation step prior to deployment create cmd to check if all the pre-req's are in place 

**Describe alternatives you've considered**
none so far and was advised by @mosabami to create this feature req

**Additional context**
n/a

**Comment by Gordonby** [comment]
In the CI/CD we do this.
https://github.com/Azure/AKS-Construction/blob/main/.github/workflows/ByoVnetCI.yml#L189

It's quite hard in the Helper to perform all these checks whilst keeping the experience simple. I think we'd need to try and work out if this is feasible.

**Comment by Gordonby** [comment]
Closely relates to #421
