### ISSUE TITLE
Expand the list of VM SKU's in the Helper dropdown

### ISSUE THREAD

**Issue by Gordonby** [Azure/AKS-Construction#393]
`Feedback from Cloud Native Hack Hours`

Vm skus that support cache as well as temp storage can be used with ephemeral storage if the OS disk size is changed to fit the cache or temp storage size. can you support that in AKS-Construction?
For example Standard_D2d_v5 has 75Gb temp storage and could use ephemeral storage as long as the OS disk size is set accordingly

**Comment by fireblade95402** [comment]
There's also an option to use the api to get the list of sku's in a region. 

https://management.azure.com/subscriptions/{{subscriptionId}}/providers/Microsoft.Batch/locations/ukwest/virtualMachineSkus?$filter=&api-version=2022-06-01

Then filter the list on "EphemeralOSDiskSupported". 

Wonder if this would work?

**Comment by fireblade95402** [comment]
FYI, @Gordonby 

 Added a change to load the VM Sku's from a json file. Place added a property "location" which to filter by location from screen and also have a "global" value for all locations. Next step would be to create a process to generate the file from the build. As least it is now not hard coded. See example of json below:

`[
{ "key": "b", "text": "Burstable (dev/test)", "itemType": "DropdownMenuItemType.Header", "location": "global"},
{ "key": "Standard_B2s", "text": "2 vCPU,  4 GiB RAM,   8GiB SSD, 40% -> 200% CPU", "eph": false, "location": "global"},
{ "key": "dv2", "text": "General purpose V2", "itemType": "DropdownMenuItemType.Header", "location": "global" },
{ "key": "default", "text": "2 vCPU,  7 GiB RAM,  14GiB SSD,  86 GiB cache (8000 IOPS)", "eph": false, "location": "global" },
{ "key": "Standard_DS3_v2", "text": "4 vCPU, 14 GiB RAM,  28GiB SSD, 172 GiB cache (16000 IOPS)", "eph": true, "location": "global" },
{ "key": "dv4", "text": "General purpose V4", "itemType": "DropdownMenuItemType.Header", "location": "global" },
{ "key": "Standard_D2ds_v4", "text": "2 vCPU,  8 GiB RAM,  75GiB SSD,               (19000 IOPS)", "eph": false, "location": "global" },
{ "key": "Standard_D4ds_v4", "text": "4 vCPU, 16 GiB RAM, 150GiB SSD, 100 GiB cache (38500 IOPS)", "eph": false, "location": "global" },
{ "key": "Standard_D8ds_v4", "text": "8 vCPU, 32 GiB RAM, 300GiB SSD,               (77000 IOPS)", "eph": true, "location": "global" },
{ "key": "fv2", "text": "Compute optimized", "itemType": "DropdownMenuItemType.Header", "location": "global" },
{ "key": "Standard_F2s_v2", "text": "2 vCPU,  4 GiB RAM,  16GiB SSD,               (3200 IOPS)", "eph": false, "location": "global" },
{ "key": "TEST", "text": "TEST", "eph": true, "location": "uksouth" }
]
`

I did make a mistake by committing it to my feature branch for the PowerShell change. So, both will now by linked.
