### ISSUE TITLE
Enabling NSG Flow logs will cause a dependency failure 

### ISSUE THREAD

**Issue by naioja** [Azure/AKS-Construction#410]
**Describe the bug**
Enabling NSG Flow logs will cause a dependency failure

**To Reproduce**
1.In the Networking Details tab 
2. Enable "Limit Ingress/Egress subnets with Network Security Groups (NGS's)"
3. Enable "Capture NSG Flow Logs with Network Watcher"
4. Causes the dependency error below 
```
{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "ResourceGroupNotFound",
      "message": "Resource group 'NetworkWatcherRG' could not be found."
    }
  ]
}
```

**Expected behavior**
Enabling both NSG option would not cause a dependency issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/6505576/190638886-72f56a31-a371-49c7-b676-a63ddf691f8e.png)

**Comment by MattLeach25** [comment]
Looked into this. First investigation showing no issues. Deployed with both options ticked and no issues caused. I will reach out to Adrian for further details to see if I can replicate the issue.

**Comment by Gordonby** [comment]
I think it depends on if the subscription already uses Network Watcher in that region.
