### ISSUE TITLE
Enabling KEDA fails as it's behind a preview flag

### ISSUE THREAD

**Issue by naioja** [Azure/AKS-Construction#411]
**Describe the bug**
Enabling KEDA fails as it's behind a preview flag

**To Reproduce**
1. Go to Addon Details
2. Enable "KEDA : Enable Kubernetes Event-driven Autoscaling (KEDA) on the AKS Cluster"

`{
    "status": "Failed",
    "error": {
        "code": "BadRequest",
        "message": "Feature Microsoft.ContainerService/AKS-KedaPreview is not enabled. Please see https://aka.ms/aks/previews for how to enable features."
    }
}`

**Expected behavior**
Setup the Preview flag OR warn the user that it needs to enable the preview flag for KEDA : https://docs.microsoft.com/en-us/azure/aks/keda-deploy-add-on-arm#register-the-aks-kedapreview-feature-flag

az feature register --name AKS-KedaPreview --namespace Microsoft.ContainerService
**Screenshots**
![image](https://user-images.githubusercontent.com/6505576/190642462-5696eba6-1a07-4bc3-83ba-57f68038710f.png)

**Comment by Gordonby** [comment]
Hi @naioja

Thanks for the issue 👍 

We do have a warning for all preview features, but as #384 mentions - it may be too subtle.

![image](https://user-images.githubusercontent.com/17914476/190657586-8f0e78ac-279d-4e9e-a9bd-aee7f5a5c929.png)

**Comment by naioja** [comment]
Yes, true but that is not necessarily valid for  enabling the Azure providers for KEDA and CSI.

**Comment by Gordonby** [comment]
Yep. I think we can probably add an extra link to the Helper (that you mentioned above) to give users a steer 👍

**Comment by naioja** [comment]
For example for KEDA if it's enabled as a deployment feature we can add a check if the provider is enabled
`az feature list -o table --query "[?contains(name, 'Microsoft.ContainerService/AKS-KedaPreview')].{Name:name,State:properties.state}"`
and if that's false then user can enable it:
`az feature register --name AKS-KedaPreview --namespace Microsoft.ContainerService`

**Comment by Gordonby** [comment]
I've created this issue to capture the better experience we want for this.
#421
