### ISSUE TITLE
Catch certain incompatible configurations in the UI

### ISSUE THREAD

**Issue by liamfoneill** [Azure/AKS-Construction#420]
**Describe the solution you'd like**
I would like to have the deploy helper flag if certain incompatible configuration choices are made - an example would be choosing B2s nodes sizes and also choosing ephemeral OS disks. 

**Describe alternatives you've considered**
The alternative is have ARM catch this at deploy time.

**Additional context**
![image](https://user-images.githubusercontent.com/1243172/193450350-fd7cc930-8926-48e3-bef3-d4f5c9f95443.png)

**Comment by Gordonby** [comment]
I think this is a duplicate of #383 which was fixed by #412
We just need to do a release to get this out there.

**Comment by Gordonby** [comment]
0.9.0 and the helper release should fix this
