### ISSUE TITLE
Add Planned Maintenance Configurations

### ISSUE THREAD

**Issue by Gordonby** [Azure/AKS-Construction#441]
ref: https://learn.microsoft.com/en-us/azure/aks/planned-maintenance

## scenario

I only want my nodes to be updated during a specific 1am-6am window Tues-Thur UTC.

## guidance

- To ensure proper functionality, use a maintenance window of four hours or more.

## caveats for ui

- Preview service
- Currently, performing maintenance operations are considered best-effort only and are not guaranteed to occur within a specified window.

## out of scope
- notAllowedTimes ?

**Comment by liammoat** [comment]
@Gordonby - happy to pick this up. We should setup a design call to discuss the best approach for the UI. I.e. do we want predefined maintenance windows, or should the user be able to design their own. Let's discuss 👍
