### ISSUE TITLE
Add support for enableNodePublicIP

### ISSUE THREAD

**Issue by Gordonby** [Azure/AKS-Construction#452]
Some scenarios may require nodes in a node pool to receive their own dedicated public IP addresses. A common scenario is for gaming workloads, where a console needs to make a direct connection to a cloud virtual machine to minimize hops. For more information see [assigning a public IP per node](https://learn.microsoft.com/en-us/azure/aks/use-multiple-node-pools#assign-a-public-ip-per-node-for-your-node-pools). The default is false.

enableNodePublicIP 

![image](https://user-images.githubusercontent.com/17914476/200359166-bc4ad228-8d9b-4abc-9f28-87b4bb7c9d8b.png)

**Comment by liammoat** [comment]
@Gordonby, I am looking to add support for "enableNodePublicIP". I have a couple of quick questions:

1. Do you think the option in the UI should be under the "Networking" tab?

    <img width="420" alt="image" src="https://user-images.githubusercontent.com/2767292/202196917-2da07124-578b-45ba-9671-88934968aaf0.png">

2. Should we target just the User node pool, or system too? Furthermore, can you share any insights or context on ```presets```, ```base``` and ```profile``` (see [here](https://github.com/Azure/AKS-Construction/blob/main/bicep/main.bicep#L1050-L1124)).

**Comment by Gordonby** [comment]
1. Networking seems the best place, i think
2. Given that gaming workloads seems to be the primary use case for adding this, i don't think system nodes would be running those workloads. I think we probably need to look to refactor some of the nodepool code.
