### ISSUE TITLE
AKS proxy. What for?

### ISSUE THREAD

**Issue by JulioFor** [Azure/AKS-Construction#476]
Now you can add proxy to your aks.
https://learn.microsoft.com/en-us/azure/aks/http-proxy
And if you read the article it seems like you are not going to use any other outbound system for your aks.
But when you deploy it using az cli you find that you still have to decide which "--outbound-type" you need. Even if you don't text it it gets its default value.

My question is: proxy? What for? I thought it was an alternative to outbound-type
No matter if I use proxy because I still need other outbound traffic for the whole cluster.

am I wrong?

**Comment by JulioFor** [comment]
I've tried to deploy aks with any  "--outbound-type" option plus "--http-proxy-config" and in any case you need or a public ip, a route (to a firewall), or a nat. If you don't even explicit "--outbound-type" you end up with a public ip.
Is this a bug or I am misunderstanding what is aks proxy for?

**Comment by Gordonby** [comment]
Hi @JulioFor 
Http Proxy is for when there's an existing organisational HTTP proxy that traffic **needs** to be routed through.

This repo is focussed on building AKS Environments through IaC, you might have more luck on the feature level discussion in the [technical community](https://techcommunity.microsoft.com/t5/azure-compute/bd-p/Compute). 

We did have suggestion to add the feature to AKS Construction (#305), but it's not something we're prioritizing at the moment.
