### ISSUE TITLE
Errors while running generated CLI command

### ISSUE THREAD

**Issue by ecoffman** [Azure/AKS-Construction#484]
**Describe the bug**

Errors received while running the script:

1. Unable to parse parameter: n˜
2. The vault name 'kv-[snip]t2wwucovhnneo' is already in use. Vault names are globaly unique so it is possible that the name is already taken. If you are sure that the vault name was not taken then it is possible that a vault with the same name was recently deleted but not purged after being placed in a recoverable state. If the vault is in a recoverable state then the vault will need to be purged before reusing the name. For more information about VaultAlreadyExists, soft delete and purging a vault follow this link https://go.microsoft.com/fwlink/?linkid=2147740.
3. {"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n  \"code\": \"InvalidParameter\",\r\n  \"message\": \"The value of parameter agentPoolProfile.name is invalid. Please see https://aka.ms/aks-naming-rules for more details.\",\r\n  \"subcode\": \"\",\r\n  \"target\": \"agentPoolProfile.name\"\r\n}"}]}}

 
Note: I removed the actual name we use for the kv we are trying to create.

**To Reproduce**

Use the provided link: https://azure.github.io/AKS-Construction/?preset=baselineRI&deploy.clusterName=something-dev&deploy.rg=Something-Dev&deploy.location=EastUS2&deploy.apiips=192.12.6.4%2C192.12.6.5&deploy.deployItemKey=deployArmCli&cluster.agentCount=2&cluster.maxCount=3&cluster.osDiskType=Managed&cluster.availabilityZones=no&cluster.upgradeChannel=stable&cluster.nodepoolName=node-pool-1&cluster.enable_aad=true&cluster.apisecurity=whitelist&cluster.keyVaultKms=none&addons.registry=Premium&addons.enableACRTrustPolicy=false&addons.ingress=nginx&net.maxPods=10&net.vnetprivateend=true&net.bastion=true&baselineRI=standard&deploy.kvCertSecretRole=true&deploy.enableTelemetry=false&cluster.AksPaidSkuForSLA=false&cluster.SystemPoolType=Standard&cluster.vmSize=Standard_F4s_v2&addons.csisecret=akvNew&cluster.autoscale=false&addons.azurepolicy=audit&addons.networkPolicy=none&addons.workloadIdentity=false&net.vnet_opt=custom&net.aksOutboundTrafficType=loadBalancer&net.serviceCidr=172.10.0.0%2F16+n%CB%9C

**Expected Behaviour**

For error 2, I was expecting the script to produce a KV name that is globally unique. 

For error 3, I don't know what to expect from that other than not error. 

Thanks

**Comment by ecoffman** [comment]
@MattLeach25 

Sure enough, I must have put those characters in the input field accidentally.

Regarding the globally unique string for the KV... when I get ready to rerun the script, I delete the resource group completely and start again. I always like to know that I have a clean script with acceptable choices. And that is the confusing part. I completely deleted the RG and it still fails. Maybe it just takes Azure longer to remove KV? In any case, to overcome this, I added location to uniqueString and things will work.

I was not aware of this. I have since fixed it. 

Thank you

**Comment by Gordonby** [comment]
## Key Vault Soft Delete

https://learn.microsoft.com/en-us/azure/key-vault/general/soft-delete-overview

> The ability to opt out of soft-delete is deprecated and will be removed in February 2025. See full details [here](https://learn.microsoft.com/en-us/azure/key-vault/general/soft-delete-change)
