### ISSUE TITLE
The enterprise scale, AKS baseline and others should enable uptime SLA by default

### ISSUE THREAD

**Issue by mosabami** [Azure/AKS-Construction#500]
**Describe the bug**
Uptime SLA is an important feature for AKS and provides customers with a financially backed SLA. It also provides better availability by guaranteeing at least 99.95% availability for clusters not using availability zones by up from 99.9%. This option is highlighted in the AKS LZA guidance, the AKS secure baseline reference implementation and multiple Microsoft learn docs. However the defaults for most of the presets in the deployment helper has SLA option set to free clusters

**To Reproduce**
1. Go to the helper
2. Select any of the presets eg Cluster with additional security controls, AKS secure baseline etc
3. Head to the cluster details tab and you'll see at the very top that the free option is set

**Expected behavior**
For the following presets:
1. AKS secure baseline (both options)
2. Azure landing zone (corp and online options)
3. Principle driven (when the I want a managed environment is selected as the operations principle)
4. New scenarios created in the future that are not for sandbox like deployments
should have the uptime sla option selected by default

Also, update the text explaining the uptime sla option to reflect the correct availability % numbers

**Screenshots**
![image](https://user-images.githubusercontent.com/34049862/214448740-19405e1b-9851-4c99-88d4-c3ef1d6962e0.png)
these are the files that will need to be modified to make the change (including the principles.json file)

**Additional context**
By providing those options as default, we are reinforcing the importance of uptime SLA option for clusters hosting any real workloads and making it easy for users to do the right thing without having to manually enable that configuration

**Comment by Gordonby** [comment]
##Design notes

This feature is linked to #406 - which introduces Prod and Non prod configurations for the Principle driven scenario. I'd suggest that the Principle driven config is changed via #406

In the Helper UI we should elaborate on what specifically is provided when you enable the SLA (more replicas etc).
