### ISSUE TITLE
LZ helper users should be able to deploy aks cluster with custom azure policy initiative

### ISSUE THREAD

**Issue by pratiksharma-dev** [Azure/AKS-Construction#505]
**Is your feature request related to a problem? Please describe.**
Customers usually use custom policies in an enterprise setting. LZ helper should have an option to deploy aks cluster with custom azure policy intiative

**Describe the solution you'd like**
LZ helper with provide an option to add custom policy initiative resourceId 

**Additional context on the request**
![image](https://user-images.githubusercontent.com/11813857/214709665-2e0eabfa-d796-4b01-9de9-ae6482925c75.png)
Currently LZ helper can add only Baseline and Restricted PSP initiative to AKS cluster. But if user wants to deploy AKS cluster with custom azure policy initiative then they won't be able to do so.

**Comment by Gordonby** [comment]
So the environment will already have a custom policy definition/initiative. (as per these [docs](https://techcommunity.microsoft.com/t5/azure-governance-and-management/azure-policy-for-kubernetes-releases-support-for-custom-policy/ba-p/2699466))

All the helper will need to do is make an assignment with the right effect against the custom policy.
