### ISSUE TITLE
Additional VM SKU family support

### ISSUE THREAD

**Issue by Gordonby** [Azure/AKS-Construction#508]
We need to support a new VM Sku Family to enable Standard_D4s_v3 to appear in the dropdown list.

### Context

**Describe the bug**
Shouldn't the Standard_D4s_v3 sku is not in the vm list in the helper?

It's the recommended default for windows skus

![image](https://user-images.githubusercontent.com/17914476/215135746-a201b945-b55d-478e-8c8d-2f72eac5bd4e.png)

**Comment by fireblade95402** [comment]
The list is driven from this file: https://github.com/Azure/AKS-Construction/blob/main/helper/src/skuFamilies.json
