### ISSUE TITLE
Nginx install - 404

### ISSUE THREAD

**Issue by Gordonby** [Azure/AKS-Construction#518]
Installing the NGINX ingress using the **post deploy** provided by the Helper gives me;

> Release "nginx-ingress" does not exist. Installing it now.
Error: failed to fetch https://github.com/kubernetes/ingress-nginx/releases/download/helm-chart-4.4.3/ingress-nginx-4.4.3.tgz : 404 Not Found

The release url needs to be updated, and we should consider how to
1. Detect broken links in scripts, and raise issue in this repo
2. Move to an evergreen "latest" version of dependant helm charts.

**Comment by khowling** [comment]
The 3rd party dependencies were pulled into this file that  `postdeploy.sh` uses.  Looks like didn't get round to implementing it for nginx yet.   nginx has like 3-4 containers

**Comment by khowling** [comment]
Looks like we are not pinning nginx versions & just taking the latest ("evergreen"), and hit this issue: https://github.com/kubernetes/ingress-nginx/issues/9569#issuecomment-1414027287

**Comment by Gordonby** [comment]
Tested again.

Fixed.

![image](https://user-images.githubusercontent.com/17914476/217876014-b6ac85ca-57fb-4d19-8160-9c09e746c4ca.png)
