### ISSUE TITLE
[Telemetry] Enhance the non-PII telemetry capture to improve user experience

### ISSUE THREAD

**Issue by samaea** [Azure/AKS-Construction#521]
**Is your feature request related to a problem? Please describe.**
Lack of more granular visibility around which aspects of AKSC is being utilised and where user drop offs are occurring.

**Describe the solution you'd like**
Capture additional events such as:-

- Scenario dropdown
- Preset card change
- GitHub workflow tab
- Clicks of Copy to clipboard on deploy. Also other clicks of Copy to clipboard/ save button on other tabs.

**Describe alternatives you've considered**
N/A.

**Additional context**
N/A

**Comment by Gordonby** [comment]
Closed by #539
