### ISSUE TITLE
Add confidential compute to AKS Constructor

### ISSUE THREAD

**Issue by aymenfurter** [Azure/AKS-Construction#525]
**Is your feature request related to a problem? Please describe.**
Setting up an AKS Cluster that supports confidential compute takes time. Having this covered through AKS Constructor would help accelerate initial deployments. 

**Describe the solution you'd like**
I don't have a clear solution in mind, maybe it could be added in the addon section?

**Additional context**
See: https://learn.microsoft.com/en-us/azure/confidential-computing/confidential-enclave-nodes-aks-get-started

**Comment by Gordonby** [comment]
Initial design notes;

## Helper UI
- Create Confcom checkbox in addOn tab
- Limit VM sizes to compatible SKU's, based on checkbox
- Add warning message about quota, visibility based on checkbox

## Bicep 
- Support confcom addon
