### ISSUE TITLE
OIDC issuer feature cannot be disabled

### ISSUE THREAD

**Issue by eorengoey** [Azure/AKS-Construction#531]
**Describe the bug**
I'm working in an automation that includes the AKS-Construction template and some additional tasks. I would expect to be able to re-run my pipeline but the template deployment failed since I enabled OIDC issuer.
I found this issue https://github.com/MicrosoftDocs/azure-docs/issues/104851 but the mentioned parameter (--disable-oidc-issuer) didn't work.

**To Reproduce**

#1- Deploy template with in-line parameters (Cluster creation)
az deployment group create -g MyRG  --template-uri https://github.com/Azure/AKS-Construction/releases/download/0.9.8/main.json --parameters \
	resourceName=TEST \
	AksPaidSkuForSLA=true \
	agentVMSize=Standard_D4ds_v4 \
	agentCountMax=5 \
	osDiskType=Managed \
	byoAKSSubnetId=[mySubnetId] \
	enable_aad=true \
	AksDisableLocalAccounts=true \
	enableAzureRBAC=true \
	adminPrincipalId=$(az ad signed-in-user show --query id --out tsv) \
	omsagent=true \
	retentionInDays=30 \
	openServiceMeshAddon=true \
	keyVaultAksCSI=true \
	keyVaultCreate=true \
	keyVaultOfficerRolePrincipalId=$(az ad signed-in-user show --query id --out tsv) \
	fluxGitOpsAddon=true \
	networkPluginMode=Overlay \
	ebpfDataplane=cilium		

#2- Get credentials for your new AKS cluster & login (interactive)
az aks get-credentials -g MyRG -n aks-TEST
kubelogin convert-kubeconfig
kubectl get nodes

#3- Deploy charts into cluster (nginx controller)
curl -sL https://github.com/Azure/AKS-Construction/releases/download/0.9.8/postdeploy.sh  | bash -s -- -r https://github.com/Azure/AKS-Construction/releases/download/0.9.8 \
	-p ingress=nginx
	
#4- Setup Flux extension
az k8s-extension create -g MyRG -c aks-TEST -t managedClusters --name flux --extension-type microsoft.flux --config image-automation-controller.enabled=true image-reflector-controller.enabled=true

#5- Config flux 
az k8s-configuration flux create -g MyRG -c aks-TEST -n cluster-config --namespace cluster-config -t managedClusters --scope cluster -u [repo] --branch gitopsync --ssh-private-key-file [myKey] --kustomization name=infra path=./src/deploy/kubernetes/cluster --kustomization name=MyNS 

#6- Enable OIDC
az aks update -g MyRG -n aks-TEST --enable-oidc-issuer

#7- Retry all the previous steps

**Expected behavior**
By idempotent principle, I expect to redeploy the template without issues but the automation failed and I'm not able to disable the OIDC issuer.  

**Error message**
{"code": "OIDCIssuerFeatureCannotBeDisabled", "message": "Provisioning of resource(s) for container service aks-TEST in resource group MyRG failed. Message: OIDC issuer feature cannot be disabled.. Details: "}

**Comment by Gordonby** [comment]
Sorry for missing the issue creation, looks like it slipped past most of the maintaining team. whoops.

gut is that this is a limitation of the resource provider, which most parts of are indeed designed to be idempotent.
