### ISSUE TITLE
What are the right names for the preview features?

### ISSUE THREAD

**Issue by Jaykul** [Azure/AKS-Construction#534]
I've been playing with setting up a new test cluster for a couple of evenings. It gives me this warning:

```
Your deployment contains Preview Features which may require subscription registration and have Azure Region limitations. Please ensure you have registered for these previews, and have installed the 'az extension add --name aks-preview' before running the relevant scripts.
Preview Features you have selected: createNatGateway, aksOutboundTrafficType, natGwIdleTimeout, kedaAddon, blobCSIDriver, oidcIssuer, workloadIdentity, networkPluginMode.
```

But these words don't seem to actually be the names of the Preview Features. Is there some way to to map "kedaAddon" to "Microsoft.ContainerService/AKS-KedaPreview" for instance?

The feature I'd really like is for it to generate the necessary `az feature register` commands into the prep script..

But the bottom line is, if we know what the preview features are, why are we listing them using the wrong names?

**Comment by Gordonby** [comment]
We're using the bicep parameter names, and don't maintain a map between the parameter names and the feature. 

Seems like a good idea to polish this a little as you've suggested.

**Comment by Gordonby** [comment]
@khowling - any thoughts on this one?
Could we use a simple map between parameter names and further metadata?
