### ISSUE TITLE
vnetFirewallManagementSubnetAddressPrefix is not changing

### ISSUE THREAD

**Issue by lenisha** [Azure/AKS-Construction#543]
**Describe the bug**
Creating AKS with custom Networking option option for AzureFwManagement subnet greyed out and deployment fails in conflict

![image](https://user-images.githubusercontent.com/6332907/225369321-a62b55b6-310c-4597-9eb5-c1693bf4f65a.png)

**To Reproduce**
1. Go to  Networking enable like in the screenshot above
2. Change adressIP space
3. vnetFirewallManagementSubnetAddressPrefix option is disabled and hardcoded in bicep
4. Fails in conflict with new IP space entered

**Comment by Gordonby** [comment]
The separate Management Subnet is only supported when using the Basic SKU of Azure Firewall (when deploying with AKSC).
You want to leverage it for Standard Firewall SKU @lenisha ?

---

Attempted to reproduce with this [configuration](https://azure.github.io/AKS-Construction/?ops=none&secure=low&deploy.clusterName=fwrepo&deploy.rg=gordons&net.vnet_opt=custom&net.afw=true&net.bastion=true&addons.registry=Premium&net.vnetprivateend=true&addons.acrPrivatePool=true)

![image](https://user-images.githubusercontent.com/17914476/225371483-29d956e3-a7ee-44cb-8635-668f2381ec99.png)

![image](https://user-images.githubusercontent.com/17914476/225372358-d5bb34d3-dafe-4fc9-9ffe-a538dd376196.png)

![image](https://user-images.githubusercontent.com/17914476/225376104-7547a722-9ce2-436a-aae1-c9bf89e2847a.png)

@lenisha - Can you advise what i've missed to reproduce your problem?

**Comment by lenisha** [comment]
@Gordonby  yes  I picked Standard Firewall and the only change I did change from "10.240.0.0/16" address space to "10.242.0.0/16" Ip space, and accordingly AKS Nodes subnet  and other subnets. It then failed as VNET bicep tried to create included FWManagement subnet and it's ip range was "10.240.x.x" , Bicep need to be adjusted not to create it

**Comment by Gordonby** [comment]
Thanks....  Ok, trying to repro with [this config](https://azure.github.io/AKS-Construction/?ops=none&secure=low&deploy.clusterName=fwrepo&deploy.rg=gordons&net.vnet_opt=custom&net.afw=true&net.bastion=true&addons.registry=Premium&net.vnetprivateend=true&addons.acrPrivatePool=true&net.vnetAddressPrefix=10.242.0.0%2F16&net.vnetAksSubnetAddressPrefix=10.242.0.0%2F22&net.vnetFirewallSubnetAddressPrefix=10.242.50.0%2F24&net.acrAgentPoolSubnetAddressPrefix=10.242.4.64%2F26&net.bastionSubnetAddressPrefix=10.242.4.128%2F26&net.privateLinkSubnetAddressPrefix=10.242.4.192%2F26) now :)

**Comment by Gordonby** [comment]
Repro'd.

`subnet 'AzureFirewallManagementSubnet' is not valid in virtual network 'vnet-fwrepo'`
