### ISSUE TITLE
BYON option with userDefinedRouting

### ISSUE THREAD

**Issue by lenisha** [Azure/AKS-Construction#544]
**Is your feature request related to a problem? Please describe.**
Enable scenario to install AKS into existing VNET with Existing Firewall and tunneling and aksOutboundTrafficType set to userDefinedRouting
Currently it's not an option

**Comment by Gordonby** [comment]
Good suggestion. Should be very easy to implement.

**Comment by iamvighnesh** [comment]
I am happy to pick this up. Although I will need a discussion on UI changes with you @Gordonby.
