### ISSUE TITLE
Issue with the Log Analytics Data Cap Breach Alert

### ISSUE THREAD

**Issue by joshuadmatthews** [Azure/AKS-Construction#559]
**Describe the bug**

This Bicep from https://github.com/Azure/AKS-Construction/blob/main/bicep/aksmetricalerts.bicep

```
resource Daily_data_cap_breached_for_workspace_logworkspacename_CIQ_1 'microsoft.insights/scheduledqueryrules@2022-06-15' = {
  name: 'Daily data cap breached for workspace ${resLogAnalyticsWorkspace.name} CIQ-1'
  location: parAutomationAccountLocation
  properties: {
    displayName: 'Daily data cap breached for workspace ${resLogAnalyticsWorkspace.name} CIQ-1'
    description: 'This alert monitors daily data cap defined on a workspace and fires when the daily data cap is breached.'
    severity: 1
    enabled: metricAlertsEnabled
    evaluationFrequency: evalFrequency
    scopes: [
      resLogAnalyticsWorkspace.id
    ]
    windowSize: windowSize
    autoMitigate: false
    criteria: {
      allOf: [
        {
          query: '_LogOperation | where Operation == "Data collection Status" | where Detail contains "OverQuota"'
          timeAggregation: 'Count'
          operator: 'GreaterThan'
          threshold: 0
          failingPeriods: {
            numberOfEvaluationPeriods: 1
            minFailingPeriodsToAlert: 1
          }
        }
      ]
    }
    muteActionsDuration: 'P1D'
  }
}
```

Continually returns this error

```
{
    "status": "Failed",
    "error": {
        "code": "BadRequest",
        "message": "Couldn't optimize the query because it doesn't contain the table Operation explicitly. Please add the table to the query explicitly and try again"
    }
}
```

I can't figure out a way to make it work. 

**To Reproduce**
Run the templates

**Expected behavior**
Should work

**Screenshots**

**Additional context**

**Comment by Gordonby** [comment]
## Trying to reproduce;

```bash
az deployment group create -g gordons  --template-uri https://github.com/Azure/AKS-Construction/releases/download/0.9.12/main.json --parameters \
	resourceName=logalertrepro \
	agentCount=1 \
	omsagent=true \
	retentionInDays=30 \
	logDataCap=1
```

Deployment completes successfully.

## Checking rule query

![image](https://user-images.githubusercontent.com/17914476/227877293-31e39867-420e-4044-bb39-f9aa51f2c429.png)

![image](https://user-images.githubusercontent.com/17914476/227877371-6f961db1-9ce0-44ee-9c1d-9d46a58d1021.png)


@joshuadmatthews  - where is the error surfacing itself?

**Comment by joshuadmatthews** [comment]
So full disclosure, I am using the ALZ-Bicep templates and it seems like this particular alert is not specific to AKS but more to the logging in general, so I moved this into my logging template deploy. Doesn't seem like that should have any side effect through, it's the same bicep against the same resource.  I can run the query in kusto just fine, and even setup the exact same log alert in the portal, which seemingly uses the exact same template. Can't for the life of me figure out what the problem is here. 

![image](https://user-images.githubusercontent.com/6090341/227949627-5db92f47-de13-44a0-b0f1-6387e10da490.png)


![image](https://user-images.githubusercontent.com/6090341/227949757-d825f89a-e1b0-4e3a-a1b9-9e63a6d840a4.png)

**Comment by Gordonby** [comment]
Well, I can repro it when I just deploy this bicep snippet; https://gist.github.com/Gordonby/a6f6dff6187d9db04ad8d05bcf80dc68 just not from the AKS Construction codebase.

**Comment by joshuadmatthews** [comment]
Glad it's not just me. Seems crazy that it would work in one scenario but not the other no?
