### ISSUE TITLE
Nginx Ingress Option not accepting traffic

### ISSUE THREAD

**Issue by khowling** [Azure/AKS-Construction#573]
When deploying nginx as a ingress controller, and creating a ingress resource, traffic the traffic is not avaiable. 

To Reproduce, deploy a cluster with nginx ingress controller

**Comment by khowling** [comment]
@kubernetes/ingress-nginx#9601

**Comment by khowling** [comment]
to resolve, add the following value (on bold) to the post deploy.  Need to do more testing

helm upgrade --install ${nginx_helm_release_name} ingress-nginx/ingress-nginx  
  --set controller.publishService.enabled=true 
  --set controller.metrics.enabled=true 
  **--set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-health-probe-request-path"=/healthz**
  --namespace ${nginx_namespace}

**Comment by Gordonby** [comment]
I can't seem to repro, but it looks like an easy addition to post deploy.

**Comment by khowling** [comment]
I think this is more workload related,  because the standard `dotnet new webapi` doesnt respond on the root path `/` the nginx controller SLB heath check endpoint is '/' so the traffic is not getting through.

I'll close this, but its good for a reference.
