### ISSUE TITLE
New default needed for osDiskSizeGb parameter

### ISSUE THREAD

**Issue by Gordonby** [Azure/AKS-Construction#612]
**Describe the bug**
The current default value for parameter `osDiskSizeGB` is 0.
The effect of this is that the AKS RP ignores the value and instead uses the value of 128GB.

As the size of the Ubuntu image is ~30GB, this means we're unnecessarily defaulting to a much bigger size disk than is needed.
Windows nodes, will indeed need a larger disk.

I think this is also related to #592

**To Reproduce**
Deploy a cluster and inspect the disk size

**Expected behavior**
An appropriately size disk will be chosen by AKSC to fit the requirement of either Linux or Windows. (32 or 128 i believe would be a good choice.)

**Screenshots**
![image](https://github.com/Azure/AKS-Construction/assets/17914476/976ba99a-85a0-4a92-a345-c81263222c3c)

**Additional context**

" Standard Ubuntu server image from Marketplace is about 30 GiB. The temp disk size must be equal to or larger than 30 GiB to enable Ephemeral OS disk on the temporary storage. Standard_B4ms has a temporary storage size of 32 GiB, which can fit the 30 GiB OS disk. Upon creation of the VM, the temp disk space would be 2 GiB."

"Standard Windows Server images from the Marketplace are about 127 GiB, meaning that you need a VM size with a cache equal to or larger than 127 GiB. The Standard_DS3_v2 has a cache size of 127 GiB, which is large enough. In this case, the Standard_DS3_v2 is the smallest size in the DSv2 series that you can use with this image."

ref: https://learn.microsoft.com/en-us/samples/azure-samples/aks-ephemeral-os-disk/aks-ephemeral-os-disk/

**Comment by iamvighnesh** [comment]
@Gordonby I am happy to make this quick change. I suggest we use the following:
- Linux defaults to 30Gb
- Windows defaults to 100Gb

**Comment by Gordonby** [comment]
I wonder if the Windows default could be more configurable.... 100GB would require quite a big VM to use an ephemeral disk. I'd need to check vm disk sizes, but something more like 50GB would be good.

**Comment by pjlewisuk** [comment]
Resolved in #661
