### ISSUE TITLE
Bug: AKS Construction does not pass necessary parameters for CNI Overlay networking

### ISSUE THREAD

**Issue by pjlewisuk** [Azure/AKS-Construction#617]
**Describe the bug**
When you select "CNI Overlay Network" and "Custom Networking" on the "Networking Details" tab, you get to define your custom network configuration, including parameters for **POD Network**, **Service Network** and **DNS Service IP** under **Kubernetes Networking Configuration**. However, the **Pod Network** and **Service Network** parameters are not passed into the Deployment script generated by AKS Construction:

![image](https://github.com/Azure/AKS-Construction/assets/6115202/ae4d267e-6173-4bf9-b7cc-8b11a5aa8899)

`podCidr` is missing from the deployment command:
![image](https://github.com/Azure/AKS-Construction/assets/6115202/ade6df15-ca93-4fd9-81d6-a47fcdc67b57)

**To Reproduce**
1. Go to [AKS Construction homepage](https://azure.github.io/AKS-Construction/)
2. Navigate to "Networking Details"
3. Check the "CNI Overlay Networking" box under "CNI Features"
4. Select "Custom Networking" option under "Default or Custom VNET"
5. Enter custom values for "VNET Address space", "AKS Nodes subnet", "POD Network", "Service Network", and "DNS Service IP"
6. Navigate to the "Bash" or "PowerShell" tabs under "Deploy Cluster", and examine the output
7. Note missing `podCidr` parameter (even though `networkPluginMode=Overlay` is set)

**Expected behavior**
`podCidr` parameter should get passed to the deployment command so that CNI Overlay networking is set up correctly.

**Screenshots**

**Additional context**

**Comment by khowling** [comment]
@samaea pls update with IP CIDR not passed
