### ISSUE TITLE
Fix images on the tiles

### ISSUE THREAD

**Issue by khowling** [Azure/AKS-Construction#624]
Images no longer appear on the tiles in the UI helper.

The Tile format support 2 types of graphic, either a Icon or a Image, the Icon works OK, but the Images no longer show.  For example, see the `helper/src/configpresents/entScale.json`, you can see the `imageSrc` key. 

**To Reproduce**
In the UI Helper, select any option except for 'principle driven', and the images are not appearing on the tiles.

**Comment by gcontreras3** [comment]
Hello @khowling I can fix this issue, assign it over :)

**Comment by Gordonby** [comment]
duplicate of #602  ?

**Comment by AdityaAgarwaal** [comment]
Hello @khowling I would like to contribute to this issue, kindly assign it to me. Thanks

**Comment by AdityaAgarwaal** [comment]
@khowling Your review on my current PR will be much appreciated. Thank you

**Comment by AdityaAgarwaal** [comment]
@khowling Please review my PR. Thankyou

**Comment by AdityaAgarwaal** [comment]
@khowling I have made the changes that you mentioned in my latest commit, Please review it. Thankyou.
