### ISSUE TITLE
Check bicep resource provider version & dependson syntax

### ISSUE THREAD

**Issue by khowling** [Azure/AKS-Construction#637]
Getting some Bicep linter wanrings about dependson syntax, and old resource provider versions

**Comment by Gordonby** [comment]
I can look at this @khowling with my bicep hat on. 🎩

@mosabami - you guys want to add me back some permissions in the repo? The bicep team managed to even though i'm not in the Azure/ org any longer.

**Comment by mosabami** [comment]
yeah i think thats a great idea @Gordonby

**Comment by Gordonby** [comment]
I'm back!!!! 👯‍♂️
