### ISSUE TITLE
Update the CSI Secret Identity to use a BYO Managed User and Setup the required federation

### ISSUE THREAD

**Issue by khowling** [Azure/AKS-Construction#638]
As described here 
https://learn.microsoft.com/en-us/azure/aks/csi-secrets-store-identity-access#access-with-an-azure-ad-workload-identity

**Comment by Gordonby** [comment]
It is specific to the workload (service account) - so perhaps more relevant to https://github.com/Azure-Samples/java-aks-keyvault-tls ?

**Comment by khowling** [comment]
Good Shout, but we've been having issues consuming aksc in a workload repo, selecting csi&keyvault options, then configuring the workload to use it with federated identity.  I cant see how its possible at the moment without the workload repo needing to create their own keyvault.   This pattern need attention!

**Comment by Gordonby** [comment]
Agreed, I think the app would need their own keyvault. Rbac will become tricky.
