### ISSUE TITLE
Ingress Profile, Web Application Routing not working

### ISSUE THREAD

**Issue by khowling** [Azure/AKS-Construction#644]
**Describe the bug**
Setting the parameter to true does not enable WAR.  Think we need to include dnsZone Resource Id, otherwise, will not  be enabled.

To reproduce select 'AKS Web Application Routing' as your ingress option'
Deploy the cluster
Then show the cluster properties, and
```
"ingressProfile": null,
```

We already allow capture for an existing dns zone resrouceId, so the fix should be to display the dnszone field when the web app routing option is selected (just as its displayed for other ingress options)

**Comment by samaea** [comment]
Hi @khowling has this been resolved?

**Comment by khowling** [comment]
yes, should be!
