### ISSUE TITLE
Add new Istio addon as preview feature

### ISSUE THREAD

**Issue by pjlewisuk** [Azure/AKS-Construction#655]
**Is your feature request related to a problem? Please describe.**
Istio AKS addon has been in public preview since May '23: https://github.com/Azure/AKS/issues/3649, and is likely to GA in October '23.

Deployment instructions: [Deploy Istio-based service mesh add-on for Azure Kubernetes Service (preview) - Azure Kubernetes Service | Microsoft Learn](https://learn.microsoft.com/en-gb/azure/aks/istio-deploy-addon)

**Describe the solution you'd like**
An option in AKS Construction helper to add the Istio addon

**Describe alternatives you've considered**
n/a

**Additional context**

**Comment by Gordonby** [comment]
Already done in #590  - However there are more options that we might now want to front than just turning it on.
