### ISSUE TITLE
Align default Kubernetes version with AKS service

### ISSUE THREAD

**Issue by pjlewisuk** [Azure/AKS-Construction#682]
**Is your feature request related to a problem? Please describe.**
Default Kubernetes version in AKS is now 1.27.7, need to align AKS Construction to this

**Describe the solution you'd like**
Update the default version to 1.27.7 

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by deepdolphin** [comment]
Bumped main branch to AKS 1.28.5, but still waiting for Bicep and new Helper application to be build + deployed.

**Comment by pjlewisuk** [comment]
Version bumped to 1.29.7 in #705
