### ISSUE TITLE
NAT Gateway deployment failure

### ISSUE THREAD

**Issue by samaea** [Azure/AKS-Construction#709]
**Describe the bug**
When selecting NAT Gateway as an option, it fails with the following deployment error message:-

`Invalid request body. Converting request body to a managed cluster encountered error: json: unknown field "natGatewayProfile" Check that the field is in the right location, is spelled correctly, and is supported in the API version. Visit aka.ms/aks/apiversions for more API version information.. (Code: UnmarshalError, Target: /subscriptions/0ab85873-613e-40df-9c89-5f219ece04b4/resourceGroups/az-k8s-2czh-rg/providers/Microsoft.ContainerService/managedClusters/aks-az-k8s-2czh)`

**To Reproduce**
`az deployment group create -g az-k8s-2czh-rg  --template-file ./bicep/main.bicep --parameters resourceName=az-k8s-2czh AksPaidSkuForSLA=true SystemPoolType=Standard availabilityZones="[\"1\",\"2\",\"3\"]" aksOutboundTrafficType=natGateway`

**Expected behavior**
For deployment to be successful.

**Screenshots**
![image](https://github.com/user-attachments/assets/d13d7fb9-89a3-4ea7-87b7-117f689c7756)

**Additional context**
N/A

**Comment by pjlewisuk** [comment]
Fixed with #710
